#pragma once

enum LGNC_STATUS_T
{
    LGNC_OK = 0,
    LGNC_HANDLED = 0,
    LGNC_NOT_HANDLED = -1,
    LGNC_ERROR = -1,
    LGNC_BLOCKED = -2,
    LGNC_INVALID_PARAMS = -3,
    LGNC_NOT_ENOUGH_MEMORY = -4,
    LGNC_TIMEOUT = -5,
    LGNC_NOT_SUPPORTED = -6,
    LGNC_BUFFER_FULL = -7,
    LGNC_HOST_NOT_CONNECTED = -8,
    LGNC_VERSION_MISMATCH = -9,
    LGNC_ALREADY_REGISTERED = -10,
    LGNC_LAST = -10,
    LGNC_NOT_INITIALIZED = -11,
};


typedef enum LGNC_STATUS_T LGNC_STATUS_T;
